on:
  push:
    branches:
    - main
env:
  buildConfiguration: Release
  dotnetSdkVersion: 6.0.x
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Usando .NET SDK ${{ env.dotnetSdkVersion }}
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.dotnetSdkVersion }}
    - name: Restaurando Dependências
      run: dotnet restore ${{ env.DOTNET_ROOT }}/**/*.csproj
    - name: Rodando o Build
      run: dotnet build **/*.csproj -c ${{ env.buildConfiguration }} --no-restore
    - name: Rodando Testes Automatizados
      run: dotnet test **/Optsol.Components.Test.*/*.csproj -c ${{ env.buildConfiguration }} --no-restore --no-build --collect "Code coverage"
    - name: Criando Pacotes Nuget
      run: |
        dotnet custom **/src/*Components*/*.csproj -c ${{ env.buildConfiguration }} --no-restore --no-build -o packages 
        dotnet custom !**/*.Test.*/*.csproj -c ${{ env.buildConfiguration }} --no-restore --no-build -o packages 
        dotnet custom !**/playground/ -c ${{ env.buildConfiguration }} --no-restore --no-build -o packages
    - name: Copiando Pacotes
      run: Copy '${{ github.workspace }}/packages/*.nupkg' '${{ github.workspace }}'
    - name: Publicando Artefato
      uses: actions/upload-artifact@v2
      with:
        path: ${{ github.workspace }}
        name: drop
                    
